[package]
name = "tabplayer_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
quick-xml.workspace = true
serde.workspace = true
serde_json.workspace = true
rkyv.workspace = true
tracing.workspace = true
rocksmith2014-psarc = { git = "https://github.com/santzit/Rocksmith2014.rs", package = "rocksmith2014-psarc" }
rocksmith2014-xml = { git = "https://github.com/santzit/Rocksmith2014.rs", package = "rocksmith2014-xml" }
rocksmith2014-sng = { git = "https://github.com/santzit/Rocksmith2014.rs", package = "rocksmith2014-sng" }
tabplayer_ffi = { path = "../ffi" }
once_cell.workspace = true
